### PR TITLE
Fix "No such target" errors on incremental sync

### LINKED ISSUE #6186: superfluous errors "no such target..." on incremental sync
### Description of the bug:

> ERROR: Skipping '//:.bazelrc': no such target '//:.bazelrc': target '.bazelrc' not declared in package '' defined by /home/swang/CLionProjects/moffett/BUILD; however, a source file of this name exists.  (Perhaps add 'exports_files([".bazelrc"])' to /BUILD?)
> ERROR: Skipping '//:.bazelversion': no such target '//:.bazelversion': target '.bazelversion' not declared in package '' defined by /home/swang/CLionProjects/moffett/BUILD; however, a source file of this name exists.  (Perhaps add 'exports_files([".bazelversion"])' to /BUILD?)
> ERROR: Skipping '//:README.md': no such target '//:README.md': target 'README.md' not declared in package '' defined by /home/swang/CLionProjects/moffett/BUILD; however, a source file of this name exists.  (Perhaps add 'exports_files(["README.md"])' to /BUILD?)
> ERROR: Skipping '//:WORKSPACE': no such target '//:WORKSPACE': target 'WORKSPACE' not declared in package '' defined by /home/swang/CLionProjects/moffett/BUILD; however, a source file of this name exists.  (Perhaps add 'exports_files(["WORKSPACE"])' to /BUILD?)

It does not seem to affect the syncing of other targets, but it would be nice to not show these non-existent targets as errors.

### Which category does this issue belong to?

CLion

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

_No response_

### Which Intellij IDE are you using? Please provide the specific version.

_No response_

### What programming languages and tools are you using? Please provide specific versions.

_No response_

### What Bazel plugin version are you using?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tpasternak**
closes #6186

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

File: base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java [hunk 1]
```diff
@@ -49,10 +51,46 @@ public class BlazeIssueParser {
 
   private static final String BAZEL_BUILD_FILES_PATTERN = "(/.*?BUILD(?:\\.bazel)?)";
 
-  public static ImmutableList<BlazeIssueParser.Parser> defaultIssueParsers(
+  private static ImmutableList<Parser> commonParsers(Project project, WorkspaceRoot workspaceRoot, ProjectViewSet projectViewSet) {
+    return ImmutableList.<Parser>builder()
+            .add(
```
Comment (odisseus) [inline base/src/com/google/idea/blaze/base/issueparser/BlazeIssueParser.java:56]: Since Java 9, you can also use [`List.of(...)`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/List.html#of(E...))

**Review by mai93 — APPROVED** [review]
