### PR TITLE
fix: Exception when opening a JavaScript project

### LINKED ISSUE #6643: Bazel sync fails on CLion 2024.2
### Description of the bug:

Whenever I try to `sync` it fails with the following error:

```
java.lang.Throwable: com.google.idea.blaze.javascript.BlazeJavascriptLibrarySource <clinit> requests com.intellij.openapi.roots.libraries.LibraryKindRegistry instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.openapi.roots.libraries.LibraryKindRegistry$Companion.getInstance(LibraryKindRegistry.kt:9)
	at com.intellij.openapi.roots.libraries.LibraryKindRegistry.getInstance(LibraryKindRegistry.kt)
	at com.intellij.openapi.roots.libraries.LibraryKind.findById(LibraryKind.java:65)
	at com.google.idea.blaze.javascript.BlazeJavascriptLibrarySource.<clinit>(BlazeJavascriptLibrarySource.java:32)
	at com.google.idea.blaze.javascript.BlazeJavascriptSyncPlugin.getLibrarySource(BlazeJavascriptSyncPlugin.java:160)
	at com.google.idea.blaze.base.sync.libraries.BlazeLibraryCollector.collectLibraries(BlazeLibraryCollector.java:47)
	at com.google.idea.blaze.base.sync.libraries.BlazeLibraryCollector.getLibraries(BlazeLibraryCollector.java:35)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.finishSync(SyncPhaseCoordinator.java:636)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.runSync(SyncPhaseCoordinator.java:432)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$0(SyncPhaseCoordinator.java:259)
	at com.google.idea.blaze.base.scope.Scope.push(Scope.java:57)
	at com.google.idea.blaze.base.sync.SyncPhaseCoordinator.lambda$syncProject$1(SyncPhaseCoordinator.java:239)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTask$0(ProgressiveTaskWithProgressIndicator.java:83)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$4(ProgressiveTaskWithProgressIndicator.java:131)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:96)
	at com.google.idea.blaze.base.async.executor.ProgressiveTaskWithProgressIndicator.lambda$submitTaskWithResult$5(ProgressiveTaskWithProgressIndicator.java:131)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Which category does this issue belong to?

Intellij

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- git clone GitHub.com/cloudflare/workerd
- install bazelisk using `brew install bazelisk`
- install bazel clion plugin
- open project in clion
- sync

### Which Intellij IDE are you using? Please provide the specific version.

CLion 2024.2

### What programming languages and tools are you using? Please provide specific versions.

C++

### What Bazel plugin version are you using?

GitHub.com/cloudflare/workerd

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tpasternak**
closes #6643

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by tpasternak** [comment]
it seems to by a Python plugin problem, unfortunately, I'll let you know about the progress

File: javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptLibrarySource.java [hunk 1]
```diff
@@ -29,20 +32,22 @@ class BlazeJavascriptLibrarySource extends LibrarySource.Adapter {
 
   private BlazeJavascriptLibrarySource() {}
 
-  @Nullable static final LibraryKind JS_LIBRARY_KIND = LibraryKind.findById("javaScript");
+  static final LazyInitializer.LazyValue<LibraryKind> JS_LIBRARY_KIND = LazyInitializer.create(
+          () -> LibraryKindRegistry.getInstance().findKindById("javaScript")
```
Comment (ujohnny) [inline javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptLibrarySource.java:36]: why not just `-> LibraryKind.findById`?

**Review by ujohnny — APPROVED** [review]

File: javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptLibrarySource.java (hunk 1 above)
Comment (tpasternak) [reply javascript/src/com/google/idea/blaze/javascript/BlazeJavascriptLibrarySource.java:36]: it's deprecated in favor if this one
