### PR TITLE
fix(qsync): IJ incorrectly recognizes files as external and asks to a…

### LINKED ISSUE #6963: For projects containing `directories: .`, files can be incorrectly recognized as external ones
### Description of the bug:

As a result, IJ asks "Do you want to add this file...?"
image

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

_No response_

### Which Intellij IDE are you using? Please provide the specific version.

_No response_

### What programming languages and tools are you using? Please provide specific versions.

_No response_

### What Bazel plugin version are you using?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tpasternak**
…dd them the the PV

fixes #6963

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Review by LeFrosch — APPROVED** [review]
No conflicts with aosp. LGTM.

File: querysync/java/com/google/idea/blaze/qsync/project/ProjectDefinition.java [hunk 1]
```diff
@@ -172,7 +172,9 @@ public boolean isExcluded(Path workspacePath) {
    */
   public Optional<Path> getIncludingContentRoot(Path workspacePath) {
     Optional<Path> contentRoot =
-        projectIncludes().stream().filter(workspacePath::startsWith).findAny();
+            projectIncludes().stream()
+                    .filter(projectInclude -> projectInclude.toString().isEmpty() || workspacePath.startsWith(projectInclude))
```
Comment (mai93) [inline querysync/java/com/google/idea/blaze/qsync/project/ProjectDefinition.java:176]: @tpasternak what if the file is really outside the workspace, this means that if `directories: .` is used no file will get the "Add file to project" action?
