### PR TITLE
fix: Resolve query failure when there is a large number of files in t…

### LINKED ISSUE #6478: When working set is too large Bazel Sync is failing with the error "Argument list too long"
### Description of the bug:

```
Error:Cannot run program....bazel" (in directory "/...."): error=7, Argument list too long
Error:Querying blaze targets building project source files failed.
```

With:
```
Computing VCS working set...
.....
  (and 3296 more)

12:59:31	Initial directory update started
12:59:47	Initial directory update finished
12:59:47	Sync started
13:00:02	Sync finished with errors
```

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Have a huge working set (one of possible cases is when your local is way behind upstream).
2. Run Bazel Sync

### Which Intellij IDE are you using? Please provide the specific version.

Intellij 2024.1.2

### What programming languages and tools are you using? Please provide specific versions.

Java

### What Bazel plugin version are you using?

2024.05.21.0.1-api-version-241

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tpasternak**
…he Working Set

closes #6478

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Comment by tpasternak** [comment]
@sgowroji "Auto Add Labels and Assignees" seems to fail

**Comment by sgowroji** [comment]
This is due to recent changes from renovate-bot PR's on github actions, which upgraded from v4 to v7.  So many Github api's and params are upgraded.  I will send a PR to fix the above failures. I will add labels and assignees manually.

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java [hunk 1]
```diff
@@ -201,7 +210,27 @@ private static ImmutableList<TargetInfo> getTargetInfoList(
       return blazeQueryLabelKindParser.getTargets();
     } catch (IOException e) {
       throw new BlazeQuerySourceToTargetException("Failed to get target info list", e);
+    } finally {
+      if (!Registry.get("bazel.sync.keep.query.files").asBoolean()) {
```
Comment (ujohnny) [inline base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java:214]: you can get boolean right from Registry without `asBoolean`

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java [hunk 2]
```diff
@@ -201,7 +210,27 @@ private static ImmutableList<TargetInfo> getTargetInfoList(
...
+        queryFile.toFile().delete();
+      }
+    }
+  }
+
+  private static @NotNull Path prepareQueryFile(Project project, String rdepsQuery) throws BlazeQuerySourceToTargetException {
+    Path queryFile = null;
```
Comment (ujohnny) [inline base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java:221]: can we rewrite this function with nio only? ie `Files.createDirectory ` and so on?

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java [hunk 3]
```diff
@@ -201,7 +210,27 @@ private static ImmutableList<TargetInfo> getTargetInfoList(
...
+    try {
+      Path queriesDir = Paths.get(project.getBasePath()).resolve("queries");
```
Comment (ujohnny) [inline base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java:223]: I suspect this should be store in tmpdir and not somewhere inside the project

**Review by ujohnny — CHANGES_REQUESTED** [review]

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java (hunk 1 above)
Comment (tpasternak) [reply base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java:214]: How can I do it?

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java (hunk 3 above)
Comment (tpasternak) [reply base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java:223]: I think it's a good practice to keep it where all internal files are. In such a case the directory permisisons are the same as the rest of the project

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java (hunk 2 above)
Comment (tpasternak) [reply base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java:220]: Done

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java (hunk 1 above)
Comment (tpasternak) [reply base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java]: Ok, done

File: base/src/META-INF/blaze-base.xml [hunk 4]
```diff
@@ -409,7 +409,9 @@
     <registryKey defaultValue="true"
                  description="By default Bazel plugin takes control and opens project if .ijwb folder is present. This property can be used to disable this behavior to allow to open .idea or other project models if they are exists."
                  key="bazel.project.auto.open.if.present"/>
-
+    <registryKey defaultValue="false"
```
Comment (mai93) [inline base/src/META-INF/blaze-base.xml:412]: is the plan to make this the default behaviour?

Comment (tpasternak) [reply base/src/META-INF/blaze-base.xml:412]: Nope, but I prefer to keep this option in case the users would like to debug or analyze performance of the query. Previously they could copy it from the cmd line. Now it's in a file disappearing right after the query is executed.

Comment (mai93) [reply base/src/META-INF/blaze-base.xml:412]: I see, I think we need to collect these registry keys and make them visible in the plugin documentation

**Review by mai93 — APPROVED** [review]

File: base/src/META-INF/blaze-base.xml (hunk 4 above)
Comment (tpasternak) [reply base/src/META-INF/blaze-base.xml:412]: Yeah, do you think it would be possible to parse these xml files to retrieve names and the descriptions, and then upload them to ij.bazel.build on regular basis?

File: base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java (hunk 3 above)
Comment (ujohnny) [reply base/src/com/google/idea/blaze/base/dependencies/BlazeQuerySourceToTargetProvider.java:229]: ok let's keep in inside the project at least for now

**Review by ujohnny — APPROVED** [review]
