### PR TITLE
fix: Support bazel 8 and `--noenable_workspace` mode

### LINKED ISSUE #6984: Sync fails without --enable_workspace
### Description of the bug:

For a bzlmod project that uses Bazel 8 where WORKSPACE approach is disabled by default, the build invocation of the plugin sync operation can fail if `--enable_workspace` is not specified. 

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

You can import the python example project from this branch https://github.com/bazelbuild/intellij/tree/bazel-8/examples/python (modified to use Bazel 8 rc). The initial sync will fail with:

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.IllegalStateException: Evaluation of SkyKey failed and no dependencies were requested: KeyForBuild{label=@@intellij_aspect//:intellij_info_bundled.bzl, isBuildPrelude=false} IncrementalInMemoryNodeEntry{key=KeyForBuild{label=@@intellij_aspect//:intellij_info_bundled.bzl, isBuildPrelude=false}, value=null, dirtyBuildingState=InitialBuildingState{state=REBUILDING, signaledDeps=6, externalDeps=0, dirtyDirectDepIndex=0}, version=com.google.devtools.build.skyframe.Version$MinimalVersion@4e5f9c78, directDeps=GroupedDeps{size=6, elements=[PRECOMPUTED:autoload_symbols, Starlark @_builtins, CONTAINING_PACKAGE_LOOKUP:@@intellij_aspect//, FILE:[/usr/local/google/home/messa/.cache/bazel/_bazel_messa/33693a4fea7b855dcfbe5494050fe249/external/intellij_aspect]/[intellij_info_bundled.bzl], PRECOMPUTED:starlark_semantics, Key{repoName=@@intellij_aspect, rootModuleShouldSeeWorkspaceRepos=true}]}, reverseDeps=ReverseDeps{reverseDeps=[], singleReverseDep=false, dataToConsolidate=[BuildTopLevelAspectsDetailsKey{topLevelAspectsClasses=[@@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect], topLevelAspectsParameters={}}]}}
	at com.google.common.base.Preconditions.checkState(Preconditions.java:838)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:697)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:435)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

The error is gone when `--enable_workspace` is added. Do we have plans to address this by passing `--enable_workapce` by default for now or some other way?

### Which Intellij IDE are you using? Please provide the specific version.

_No response_

### What programming languages and tools are you using? Please provide specific versions.

_No response_

### What Bazel plugin version are you using?

_No response_

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/22691#issuecomment-2371654429

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tpasternak**
closes #6984

there's still a known limitation - you can't downgrade Bazel from 8 to 7, but I'll handle that later

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

File: base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java [hunk 1]
```diff
@@ -58,7 +58,10 @@ public Optional<File> aspectTemplateDirectory() {
   @VisibleForTesting
   public AspectStrategyBazel(BlazeVersionData versionData) {
     super(/* aspectSupportsDirectDepsTrimming= */ true);
-    if (versionData.bazelIsAtLeastVersion(6, 0, 0)) {
+    boolean useInjectedRepository = versionData.bazelIsAtLeastVersion(8, 0, 0);
+    if (useInjectedRepository) {
+      aspectFlag = "--aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect";
```
Comment (mai93) [inline base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java:63]: why do we have to bring this to a single `@`?

Comment (tpasternak) [reply base/src/com/google/idea/blaze/base/sync/aspects/strategy/AspectStrategyBazel.java:63]: https://github.com/bazelbuild/bazel/issues/22691#issuecomment-2472920470

**Review by mai93 — APPROVED** [review]
