### PR TITLE
Highlighting support for binary operators and augmented assignments in BUILD files.

### LINKED ISSUE #7733: `|=` operator is apparently not supported in Starlark
### Description of the bug:

Image

Plain `|` is supported, and `&=` and `^=` are also supported.

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Just use `|=` somewhere in Starlark file. All uses seem to have red squiggles, regardless of the context.

### Which Intellij IDE are you using? Please provide the specific version.

IntelliJ IDEA 2025.1.1.1 (Ultimate Edition)

### What programming languages and tools are you using? Please provide specific versions.

Just Starlark code is enough to repro the error

### What Bazel plugin version are you using?

2025-04-30.0

### Have you found anything relevant by searching the web?

Nothing, unfortunately :/

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by odisseus**
Supported operators: `& ^ >> << &= ^= |= >>= <<=`

Fixes #7733.

### CODE REVIEW

File: base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java [hunk 1]
```diff
@@ -769,10 +772,28 @@ private void tokenize() {
           popParen();
           break;
         case '>':
-          addToken(TokenKind.GREATER, pos - 1, pos);
+          if (lookaheadIs(0, '>') && lookaheadIs(1, '=')) {
```
Comment (LeFrosch) [inline base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java:775]: Maybe we can add a tokenize three chars and move the rest (<<, >>) also to two chars?

**Review by LeFrosch — CHANGES_REQUESTED** [review]
This pre grammar kit stuff is fun lamo

File: base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java (hunk 1 above)
Comment (odisseus) [reply base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java:775]: I just copied the code which handles `//=`. Sure, this whole class could use some refactoring (personally I would prefer using something like ANTLR to generate the parser), but I want to keep my changes as simple and straightforward as possible.

Comment (LeFrosch) [reply base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java:775]: I mean, I just wanted to suggest to stick with the structure that's already there. Like, to put the parsing for 2-token operators into the 2-token-method.

Comment (odisseus) [reply base/src/com/google/idea/blaze/base/lang/buildfile/lexer/BuildLexerBase.java:775]: I don't quite understand what you're objecting to. "Stick with the structure that's already there" is exactly what I did here. See line 830 for comparison.
