### PR TITLE
Fix for wrong compiler executable when using custom toolchains

### LINKED ISSUE #6418: CLion does not find the right compiler when using a custom toolchain
### Description of the bug:

When the toolchain is configured using `action_configs` instead of `tool_paths` the path returned by `CcToolchainInfo.compiler_executable` seems to be wrong.

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

_No response_

### Which Intellij IDE are you using? Please provide the specific version.

_No response_

### What programming languages and tools are you using? Please provide specific versions.

_No response_

### What Bazel plugin version are you using?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by LeFrosch**
# Checklist

- [x] I have filed an issue about this change and discussed potential changes with the maintainers.
- [x] I have received the approval from the maintainers to make this change.
- [x] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: #6418

# Description of this change
Fixes #6418 by using `cc_common.get_tool_for_action` to find the right c and cpp compiler executable.

### CODE REVIEW

File: cpp/src/com/google/idea/blaze/cpp/BlazeConfigurationResolver.java [hunk 1]
```diff
@@ -133,12 +133,12 @@ private static ImmutableMap<String, String> getTargetToVersionMap(ImmutableMap<T
     ImmutableMap<ExecutionRootPath, String> compilerVersionByPath =
             compilerSettings.entrySet().stream().collect(
                     ImmutableMap.toImmutableMap(
-                            e -> e.getKey().getCppExecutable(),
-                            e -> e.getValue().getCompilerVersion()));
+                            e -> e.getKey().getCppCompiler(),
+                            e -> e.getValue().getCppCompilerVersion()));
```
Comment (LeFrosch) [inline cpp/src/com/google/idea/blaze/cpp/BlazeConfigurationResolver.java:137]: This not correct and I already had a simple fix for `BlazeCompilerInfoMapService`. But maybe it is worth taking a closer look considering #6410. Since this would require more changes I would like to merge this first.

**Review by ujohnny — CHANGES_REQUESTED** [review]

**Review by ujohnny — APPROVED** [review]
lgtm
