### PR TITLE
fix(qsync): NPE in "Add to project" panel action

### LINKED ISSUE #6966: Query Sync: Add file to proejct doesn't work
### Description of the bug:

https://github.com/user-attachments/assets/79523dda-48b9-41ce-af9d-967a0be3f713

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

_No response_

### Which Intellij IDE are you using? Please provide the specific version.

_No response_

### What programming languages and tools are you using? Please provide specific versions.

_No response_

### What Bazel plugin version are you using?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tpasternak**
A comment contains a warning that there should be at least two packages found in order to provide user a choice. However in some cases there is only a single package to add.

For this reason, we stop the lookup if it reaches project root, but we don't add a package automatically, so a user can always reject the change.

closes #6966

https://github.com/user-attachments/assets/593377c4-84d6-48e1-89a5-6ebc9beb0c9e

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

Issue number: `<please reference the issue number or url here>`

# Description of this change

### CODE REVIEW

**Review by xuansontrinh — APPROVED** [review]

File: base/src/com/google/idea/blaze/base/qsync/CandidatePackageFinder.java [hunk 1]
```diff
@@ -90,14 +90,16 @@ public ImmutableList<CandidatePackage> getCandidatePackages(
...
+    // in such a case, we return it, but we don't add it unconditionally.
     do {
       cancellationCheck.run();
       packages = runQuery(forPath);
       if (!packages.isEmpty()) {
         candidates.add(new CandidatePackage(forPath, packages.size()));
       }
       forPath = forPath.getParent();
-    } while (candidates.size() < 2 && packages.size() < 2);
+    } while (candidates.size() < 2 && packages.size() < 2 && forPath != null);
```
Comment (ujohnny) [inline base/src/com/google/idea/blaze/base/qsync/CandidatePackageFinder.java:102]: `forPath != null`

this could become an infinite loop

>Returns the parent path, or null if this path does not have a parent.

Comment (tpasternak) [reply base/src/com/google/idea/blaze/base/qsync/CandidatePackageFinder.java:102]: what do you mean?

Comment (tpasternak) [reply base/src/com/google/idea/blaze/base/qsync/CandidatePackageFinder.java:102]: it's a `Path`, running .getParent on it must end with a null eventually

Comment (ujohnny) [reply base/src/com/google/idea/blaze/base/qsync/CandidatePackageFinder.java:102]: oh, my bad, I'm so sorry about that

**Review by ujohnny — APPROVED** [review]
