### PR TITLE
fix: deadlock when more than one project is open and bazel.sync.detec…

### LINKED ISSUE #5979: Freeze when jumping into definition with bazel.sync.detect.source.roots
### Description of the bug:

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Make sure there's any project already imported in IntelliJ window
2. Double-press shift -> "Registry..." -> "bazel.sync.detect.source.roots" -> enable
3. Click file -> import bazel project
4. Choose examples/java/greetings_project
5. Choose hi/hi.bazelproject
6. Remove `greeting_lib` from the project view file
7. Click Finish
8. **Choose "open in new window** option when IntelilJ asks
9. Go to HiGreeter.java
10. Jump to the definition of the `getGreetings` method (ctrl+click the method)

Expected result:
jumps to definition

Observed result:
Deadlock, infinte hang

### Which Intellij IDE are you using? Please provide the specific version.

_No response_

### What programming languages and tools are you using? Please provide specific versions.

_No response_

### What Bazel plugin version are you using?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tpasternak**
…t.source.roots is enabled

# Checklist

- [ ] I have filed an issue about this change and discussed potential changes with the maintainers.
- [ ] I have received the approval from the maintainers to make this change.
- [ ] This is not a stylistic, refactoring, or cleanup change.

Please note that the maintainers will not be reviewing this change until all checkboxes are ticked. See 
the [Contributions](https://github.com/bazelbuild/intellij#contributions) section in the README for more 
details.

# Discussion thread for this change

closes #5979 

# Description of this change

### CODE REVIEW

File: java/src/com/google/idea/blaze/java/sync/model/BlazeJarLibrary.java [hunk 1]
```diff
@@ -31,6 +31,7 @@
 import com.google.idea.blaze.java.libraries.AttachedSourceJarManager;
 import com.google.idea.blaze.java.libraries.JarCache;
 import com.intellij.openapi.diagnostic.Logger;
+import com.intellij.openapi.progress.ProgressManager;
```
Comment (dkashyn-sfdc) [inline java/src/com/google/idea/blaze/java/sync/model/BlazeJarLibrary.java:34]: old import is not required anymore

**Review by agluszak — APPROVED** [review]
